
backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

site_url: "https://TU-DOMINIO.com"

collections:
  - name: "videos"
    label: "Videos"
    folder: "src/videos"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", hint: "sin espacios, ej: labial-mate"}
      - {label: "YouTube URL", name: "youtube", widget: "string"}
      - {label: "Miniatura (OG)", name: "thumbnail", widget: "image", allow_multiple: false}
      - {label: "Etiqueta", name: "tag", widget: "string", required: false}
      - {label: "Descripción", name: "description", widget: "text", required: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "video.njk"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/v/{{slug}}/index.html"}
